### ISSUE TITLE
Removing intermediate files of tenant override logic if pipeline submission fails

### ISSUE THREAD

**Issue by haozhestat** [Azure/shrike#230]
**Before filing, make sure to upgrade to the latest shrike version and check if the bug reproduces.**

**Category**
Please select:
- [x] shrike.pipeline
- [ ] shrike.build
- [ ] shrike.compliant_logging

Please also add corresponding labels.

**Describe the bug**
This issue was first reported in the stack overflow: https://stackoverflow.microsoft.com/questions/281579

There are several modules which will run and test on eyes-off and eyes-on personal workspace. There are several difference between eyes-off and eyes-on configuration yaml, and with the feature `tenant_overrides`, I can resolve some but not all of them.

Some of the differences can be handle by `tenant_overrides` like follows.

1. `eyes-off` environment using python pkg_idx like `https://o365exchange.pkgs.visualstudio.com/_packaging/PolymerPythonPackages/pypi/simple/`, which are not available in eyes-on environment. And based on `remove_polymer_pkg_idx: true` I can remove the index.
2. `docker image` are not the same since eyes-on can't access polymer docker image. I can also using mapping logic to change them to others.

I did find a difference which can't be handle by current logic. That is, in eyes-on environment, I need add `conda-forge` as one of the channels to install package like `pythonnet` and `mono`. You can see the difference [here](https://o365exchange.visualstudio.com/O365%20Core/_git/SearchRelevance?path=/sources/dev/searchrel/steps/aml/related-search-search-result-gen/local_default_env.yaml&version=GBmaster&line=2&lineEnd=4&lineStartColumn=1&lineEndColumn=16&lineStyle=plain&_a=contents)
I don't know how to add additional channels to the `tenant_override` yaml for this, what I've wrote is like follows:

```
tenant_overrides:   
  allow_override: true   
  keep_modified_files: false   
  mapping:     # Eyes-on tenant     
    72f988bf-86f1-41af-91ab-2d7cd011db47:       
      remove_polymer_pkg_idx: true
      environment.docker.image:
     'polymerprod.azurecr.io/polymercd/prod_official/azureml_base_cpu_openmpi312_ubuntu1804(.+)': "mcr.microsoft.com/azureml/base-gpu:openmpi3.1.2-cuda10.1-cudnn7-ubuntu18.04"
      tags:
        workspace: eyeson
```

What's more, I found the solution of the `tenant_override` seems to be following steps:
1. Backup the `module_spec.yaml` to `module_spec.not_used`
2. Change the value in `module_spec.yaml` directly.
3. Submit the pipeline.
4. Recover the `module_spec.not_used` to `module_spec.yaml`

When there is any exception in submit, no recover will process. Then in my local directory, there will be a lot of changed `module_spec.yaml` and `module_spec.not_used`.
