### ISSUE TITLE
Pipelines functionality should support submission-time "swap" of Docker images

### ISSUE THREAD

**Issue by dkmiller** [Azure/shrike#34]
Currently, a component spec may make itself unusable in "public" workspace by pointing to a Docker image in a tightly controlled ACR, e.g.:

```yaml
environment:
  docker:
    image: somesupersecretfeed.azurecr.io/some/image/path:tag
```

This library should consider exposing a configuration value (or, potentially, read this information from AAD tenant?) on which it will re-write the component spec files _before_ they're loaded. The users could, e.g., configure a default "public" base image / image(s), potentially indexed by OS and CPU vs. GPU. Alternatively, the library could come with a default set of "public" images, which are configurable / overrideable.

More design work is needed!
