### ISSUE TITLE
The "pipelines" part of this library should allow submission-time image override

### ISSUE THREAD

**Issue by dkmiller** [Azure/shrike#43]
It'll have to be hacky &mdash; edit the **files** (component specs) just before pipeline submission, then revert after submission.

More design work is needed, i.e. how to detect when to do this and/or how to configure.

**Comment by danrsc** [comment]
Is this feature intended to allow multiple workspace components or something else? In my library, I have modified the graph_node decorator to allow a dictionary mapping from a friendly workspace file name (e.g. eyes_on) to a docker image. The same could be done for other aspects of the component spec. Then, the idea is that the build registers the appropriate variant I'm the appropriate workspace. Not as good as dynamic, but given compliance constraints, this may be a less "hacky" way to get the desired outcome

**Comment by dkmiller** [comment]
@danrsc yes, this feature is intended to allow the component to operate across multiple workspaces, with an especial view towards **local copies** of the component (for remote copies, we'd need logic in the build tooling).

And yes, it's not quite clear what's the best way to configure, but I could see something like:

```yaml
tenant_overrides:
    # MSIT tenant
    72f988bf-86f1-41af-91ab-2d7cd011db47:
      # YAML path -> overrides on values, could potentially have regexes in keys as well?
      environment.docker.image:
        polymerprod.azurecr.io/polymercd/prod_official/azureml_base_gpu_openmpi312cuda101cudnn7: mcr.microsoft.com/azureml/openmpi3.1.2-cuda10.1-cudnn7-ubuntu18.04
# ... other mappings as well
```

thoughts?

**Comment by danrsc** [comment]
@dkmiller If I can put in a plug here, one nice thing about aml-graph-node is the tooling works locally too :). Setting that aside, for unpublished components, can't the upcoming AML features that dynamically override be leveraged? The other thing I would think of is to just have multiple environments in the component spec - i.e. change the schema to allow multiple environment sections. Then have a condition attribute on each environment (or a workspace attribute if we want to keep it restricted to just workspace), and fall through to the default one if the specific one doesn't have one of the attributes of the environment section. In ADO build this could be transformed to the normal schema for the workspace, and on the dev machine this could be copied to a temporary location and transformed appropriately. To me it is easier to read the multiple environments than the separate override section, but not a big deal. I think either is good

**Comment by dkmiller** [comment]
@danrsc - the goal here is to implement this for local.

The feature ask (dynamic environment override) was explicitly rejected by Office compliance, so we're proposing the next best thing here.

Otherwise, good suggestions! We'll look more closely when we have bandwidth to implement this (hopefully soon) :)

**Comment by fuhuifang** [comment]
In terms of design, how would we want to implement the command line override syntax? One complex scenario is the user wants to override 2+ images, and each image is applied to 2+ components. My initial thoughts would be to use dictionary of image: component_key pairs:
```python
python pipeline.py --override_image: {"polymerprod.azurecr.io/polymercd/image1": ["Component1", "Component2"], "polymerprod.azurecr.io/polymercd/image2": ["Component3"]}
```
What do you think @dkmiller @haozhestat ?

**Comment by fuhuifang** [comment]
Copied from duplicate issue #34 :

The Polymer team now has an MSIT-tenant ACR that they're connecting with MyData workspaces. While the base URL and (first part) of the image path are different, the contents are identical.

That makes this functionality a bit more valuable.

**Comment by dkmiller** [comment]
Concerns:

- This would edit the users' YAML files. Potential for concern with registered components.
- We would then have to support editing all _other_ fields (tags, etc.)
- MCR and Polymer have different image names, both of which may change over time. There's no clear 1:1 mapping.

Also, Office will move MyData workspaces into Torus tenant, with direct access to the Polymer ACR.

For switching between eyes-off and eyes-on, you need to update:

- image (currently painful)
- compute (already supported)
- input data (already supported)

**Comment by fuhuifang** [comment]
RFC: https://github.com/Azure/shrike/blob/main/docs/rfc/pipeline-image-override.md

**Comment by evgri243** [comment]
Upvoting! 👍  Just checked that polymer dev (polymerdev.azurecr.io/polymercd/dev_official/azureml_base_cpu:latest) works perfectly in MyData.

**Comment by evgri243** [comment]
@dkmiller @fuhuifang I was finking today that your proposal won't work for component publishing in AML CLI, and thinking about that ended up with a different idea on how to implement it. But I believe it will require to make changed in Component SDK and Runtime instead of shrike.

But shortly, what if Component SDK will provide a way to inherit spec files, them we can have something like that:

module_spec.yaml:
```yaml
$schema: http://azureml/sdk-1-5/ParallelComponent.json
name: sample_component
type: CommandComponent
inputs:
  input_path:
    type: AnyDirectory
outputs:
  output_path:
    type: AnyDirectory
    description: output file where tagged text will be written
<...>
environment:
  docker:
    image: polymerprod.azurecr.io/polymercd/prod_official/azureml_base_cpu:latest
  os: Linux

```
And then override module_spec_personal.yaml:
```yaml
$inherits: module_spec.yaml
environment:
  docker:
    image: polymerdev.azurecr.io/polymercd/dev_official/azureml_base_cpu:latest
```

In that case we can load it with load_yaml("sample_component/module_spec_personal.yaml) if needed or in shrike's vision define two module files:

modules-default.yaml:
```yaml
anifest:
  - key: "SampleComponent"
    name: "sample_component"
    version: null
    yaml: "sample_component/module_spec.yaml"
```

and modules-personal.yaml:
```yaml
manifest:
  - key: "SampleComponent"
    name: "sample_component"
    version: null
    yaml: "sample_component/module_spec_personal.yaml"
```

And with pipeline config like that:
```yaml
defaults:
  - aml: eyes-off
  - compute: eyes-off
  - modules: modules-defaults
```

while submitting pipeline to eyes-on just call: `python src/pipelines/sample_pipeline.py --config-dir ./conf --config-name reference/sample_pipeline.yaml run.submit=True default.modules=modules-personal.yaml`

This should make that hack a little more universal and applicable to other scenarios, not just polymer-specific registry workaround and keep compatibility and automatic inference with the most of existing tools (Azure CLI, non-shrike SDKs etc)

Going forward with that design we can also think of (optional):
* inputs/output merge can be implemented to allow overrides as well as definition of new parameters
* convention inference like module_spec_{environment}.yaml is used automatically if present (e.g. eyes-off, personal etc)

What do you think? I can prepare a formal RFC if that idea is worth considering.
